version: '3.4'

services:
  db:
    image: mariadb
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-whocares}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wordpress}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}

  cli:
    image: devops
    env_file: .env
    depends_on:
      - db
    volumes:
      - wp_volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      WORDPRESS_DATABASE: ${MYSQL_DATABASE:-wordpress}

  wordpress:
    image: wordpress
    depends_on:
      - cli
    volumes:
      - wp_volume:/var/www/html
    ports:
      - ${WP_PORT:-1234}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      WORDPRESS_DATABASE: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_URL: www.numeration.com
    hostname: www.numeration.com

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - wp_volume:/var/www/html
    depends_on:
      - wordpress
    command: sh -c -e "echo \"server {\n\tlisten 80;\n\tserver_name www.numeration.com;\n\n\tlocation / {\n\t\tproxy_pass http://wordpress:1234;\n\t\tproxy_set_header Host $host;\n\t\tproxy_set_header X-Real-IP $remote_addr;\n\t\tproxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n\t\tproxy_set_header X-Forwarded-Proto $scheme;\n\t}\n}\" > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  db_volume:
  wp_volume: